name: myshoppinglist
description: My Shopping List App

version: 1.0.0+6

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  firebase_core : ^0.5.0
  firebase_analytics: ^6.0.2
  firebase_auth: ^0.18.1+2
  firebase_auth_web: ^0.3.1+1
  cloud_firestore: ^0.14.1+3

  font_awesome_flutter: ^8.10.0

  flutter_colorpicker: ^0.3.4
  flutter_slidable: ^0.5.7

  url_launcher: ^5.7.5
  share: ^0.6.5+3
  launch_review: ^2.0.0

  modal_progress_hud: ^0.1.3

  connectivity: ^0.4.9+5

dependency_overrides:
  url_launcher_platform_interface: 1.0.8

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/list.png